name: CI

on:
  push:
  pull_request:

jobs:
  build-vcpkg:
    name: build vcpkg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        shell: bash
        if: ${{ runner.os == 'linux' }}
        run: |
          sudo apt-get update
          # Required for libxcrypt
          sudo apt-get install libtool libltdl-dev autoconf automake pkg-config
      - name: Install cargo-vcpkg
        run: cargo install cargo-vcpkg
      - name: Install dependencies
        run: cargo vcpkg -v build
      - name: Build sdl3
        shell: bash
        env:
          CI_BUILD_FEATURES: "use-vcpkg"
          RUST_TEST_THREADS: 1
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --features "${CI_BUILD_FEATURES}"
          cargo build --examples --features "${CI_BUILD_FEATURES}"
          cargo test --features "${CI_BUILD_FEATURES}"

  build-from-source:
    name: build from source
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        feature: ["build-from-source"]
        build_mode: [""]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Build sdl3
        shell: bash
        env:
          CI_BUILD_FEATURES: ""
          RUST_TEST_THREADS: 1
        run: |
          set -xeuo pipefail
          rustc --version
          cargo --version
          cargo build --features "${CI_BUILD_FEATURES} ${{matrix.feature}}" ${{matrix.build_mode}}
          cargo build --examples --features "${CI_BUILD_FEATURES} ${{matrix.feature}}" ${{matrix.build_mode}}
          cargo test --features "${CI_BUILD_FEATURES} ${{matrix.feature}}" ${{matrix.build_mode}}
